stages:
- stage: continuous_integration
  displayName: Continuous Integration
jobs:
- job: build
  displayName: Build
  steps:
  - script: dotnet --version
     displayName: Check .NET Version
  - script: dotnet restore
    displayName: Restore NuGet Packages
  - script: dotnet build
    displayName: Build .NET Project 
  - script: dotnet build
    displayName: Run .NET Project
